In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.

# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/Kannada-MNIST/train.csv
/kaggle/input/Kannada-MNIST/sample_submission.csv
/kaggle/input/Kannada-MNIST/test.csv
/kaggle/input/Kannada-MNIST/Dig-MNIST.csv


In [2]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization, Dropout, Dense, Activation, ZeroPadding2D, Flatten
from keras.regularizers import l2
from keras.losses import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import np_utils
from keras.optimizers import Adam
from keras.callbacks import ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import numpy as np
import csv

Using TensorFlow backend.


In [3]:
def conv_layer(model, num_kernels, kernel_size=(3,3), strides=1, activation='relu', pad_mode='same',
               addBatchNorm=True, addPooling=True):
    """
    Builds the layers of convolutional neural networks with default (3,3) max pooling.

    :param model: The object of keras.models.Sequential
    :param num_kernels: Number of kernels
    :param kernel_size: Size of kernels
    :param strides: Strides of conv. layer
    :param activation: Name of activation function
    :param pad_mode: 'same'/'valid'
    :param addBatchNorm: True/False
    :param addPooling: True/False
    :return: return an object of model.
    """
    model.add(Conv2D(num_kernels, kernel_size=kernel_size, strides=strides, padding=pad_mode,
                     kernel_regularizer=l2()))
    if addBatchNorm:
        model.add(BatchNormalization(axis=3))

    model.add(Activation(activation))

    if addPooling:
        model.add(MaxPooling2D((3,3), strides=strides))

    return model

In [4]:
num_classes = 10
batch_size = 256
epochs = 200
img_x, img_y = (28, 28)
input_shape = (img_x, img_y, 1)

# Preprocessing

- We combined the **train.csv** and **Dig-MNIST.csv** together as the training dataset.

In [5]:
train_dataset1 = pd.read_csv('/kaggle/input/Kannada-MNIST/train.csv')
train_dataset2 = pd.read_csv('/kaggle/input/Kannada-MNIST/Dig-MNIST.csv')
train_dataset = train_dataset1.append(train_dataset2, ignore_index = True)
test_dataset = pd.read_csv('/kaggle/input/Kannada-MNIST/test.csv')

train_dataset.groupby(by='label').size()

label
0    7024
1    7024
2    7024
3    7024
4    7024
5    7024
6    7024
7    7024
8    7024
9    7024
dtype: int64

In [6]:
x_MNIST = train_dataset.drop(['label'], axis=1).values.reshape(-1, img_x, img_y, 1).astype('float32')/255
y_MNIST = train_dataset['label']
x_test = test_dataset.drop(["id"], axis=1).values.reshape(-1, img_x, img_y, 1).astype('float32')/255

In [7]:
x_train, x_dev, y_train_origin, y_dev_origin = train_test_split(x_MNIST, y_MNIST, test_size=0.1, random_state=0)

- Convert the **y_train** and **y_dev** into one-hot vectors.

In [8]:
y_train = np_utils.to_categorical(y_train_origin, num_classes=num_classes)
y_dev = np_utils.to_categorical(y_dev_origin, num_classes=num_classes)

- Learning rate decay.

In [9]:
lr_reduction = ReduceLROnPlateau(monitor='val_loss', patience=5, cooldown=5, factor=np.sqrt(0.5), verbose=2)

- Image data generator.

In [10]:
img_gen = ImageDataGenerator( featurewise_center=False,
                              samplewise_center=False,
                              featurewise_std_normalization=False,
                              samplewise_std_normalization=False,
                              zca_whitening=False,
                              rotation_range=10,
                              zoom_range=0.10,
                              width_shift_range=0.1,
                              height_shift_range=0.1,
                              horizontal_flip=False,
                              vertical_flip=False)

# Construct model
- Majorly, we use continuously conv_layer function to stack series **CONV layers** with the same number of kernels and that was called a group. And we connected the each group by a **Dropout layer**.
- Finally, 2 **Fully connected layers** were set behind the **Flatten**.

In [11]:
model = Sequential()
model.add(ZeroPadding2D((1,1), input_shape=input_shape))
# Group 1
model = conv_layer(model, 32, kernel_size=(5, 5), strides=1, activation='relu', pad_mode='valid', addPooling=True)
model = conv_layer(model, 32, kernel_size=(5, 5), strides=1, activation='relu', pad_mode='same', addPooling=True)
model = conv_layer(model, 32, kernel_size=(5, 5), strides=1, activation='relu', pad_mode='valid', addPooling=True)
model.add(Dropout(0.2))
# Group 2
model = conv_layer(model, 64, kernel_size=(3, 3), strides=1, activation='relu', pad_mode='valid', addPooling=True)
model = conv_layer(model, 128, kernel_size=(3, 3), strides=1, activation='relu', pad_mode='same', addPooling=False)
model = conv_layer(model, 128, kernel_size=(3, 3), strides=1, activation='relu', pad_mode='same', addPooling=False)
model = conv_layer(model, 128, kernel_size=(3, 3), strides=1, activation='relu', pad_mode='valid', addPooling=False)
model.add(Dropout(0.2))
# Group 3
model = conv_layer(model, 256, kernel_size=(3, 3), strides=1, activation='relu', pad_mode='valid', addPooling=True)

model.add(Flatten())
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.compile(optimizer=Adam(),
              loss=categorical_crossentropy,
              metrics=['accuracy'])

- Print information about this model and the data.

In [12]:
print(model.summary())
print('Size of training dataset:', x_train.shape[0])
print('Size of dev. dataset:    ', x_dev.shape[0])

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
zero_padding2d_1 (ZeroPaddin (None, 30, 30, 1)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 26, 26, 32)        832       
_________________________________________________________________
batch_normalization_1 (Batch (None, 26, 26, 32)        128       
_________________________________________________________________
activation_1 (Activation)    (None, 26, 26, 32)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 24, 24, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 32)        25632     
_________________________________________________________________
batch_normalization_2 (Batch (None, 24, 24, 32)       

- Start training.

In [13]:
img_gen.fit(x_train)
model.fit_generator(img_gen.flow(x_train, y_train, batch_size=batch_size),
                    epochs=epochs,
                    steps_per_epoch=x_train.shape[0] // batch_size,
                    verbose=2,
                    validation_data=(x_dev, y_dev),
                    callbacks=[lr_reduction])

Epoch 1/200
 - 18s - loss: 3.7106 - accuracy: 0.7196 - val_loss: 4.3849 - val_accuracy: 0.1163
Epoch 2/200
 - 15s - loss: 0.6555 - accuracy: 0.9462 - val_loss: 2.1226 - val_accuracy: 0.5214
Epoch 3/200
 - 15s - loss: 0.4318 - accuracy: 0.9526 - val_loss: 0.6905 - val_accuracy: 0.8482
Epoch 4/200
 - 15s - loss: 0.3566 - accuracy: 0.9573 - val_loss: 0.6881 - val_accuracy: 0.8612
Epoch 5/200
 - 15s - loss: 0.3281 - accuracy: 0.9591 - val_loss: 0.3914 - val_accuracy: 0.9476
Epoch 6/200
 - 15s - loss: 0.3190 - accuracy: 0.9603 - val_loss: 0.4115 - val_accuracy: 0.9224
Epoch 7/200
 - 15s - loss: 0.3106 - accuracy: 0.9617 - val_loss: 0.3323 - val_accuracy: 0.9560
Epoch 8/200
 - 15s - loss: 0.3019 - accuracy: 0.9629 - val_loss: 0.4067 - val_accuracy: 0.9285
Epoch 9/200
 - 15s - loss: 0.3031 - accuracy: 0.9618 - val_loss: 0.9623 - val_accuracy: 0.8853
Epoch 10/200
 - 15s - loss: 0.2983 - accuracy: 0.9643 - val_loss: 0.3710 - val_accuracy: 0.9469
Epoch 11/200
 - 15s - loss: 0.3005 - accuracy: 0.

# Evaluate model by testing dataset

In [14]:
print('\nPredicting...')
predictions = model.predict(x_test)
print('Prediction completed.')
predictions = np.argmax(predictions, axis=1)


Predicting...
Prediction completed.


- Save result as CSV for submission.

In [15]:
with open('07.Kaggle_submission.csv', 'w', newline='') as csv_file:
    print('\nSaving file...')
    csv_writer = csv.writer(csv_file, delimiter=',')
    # Define column name.
    csv_writer.writerow(['id', 'label'])
    for i in range(len(predictions)):
        csv_writer.writerow([i, predictions[i]])

    print('File: 07.Kaggle_submission.csv Saved completed.')


Saving file...
File: 07.Kaggle_submission.csv Saved completed.


# Confusion matrix
- We not only evaluate the performance through the accuracy in developing phase but also use the confusion matrix might be more specific this model would be trained becoming overfitting or not.

In [16]:
from sklearn.metrics import confusion_matrix
import seaborn as sn
import matplotlib.pyplot as plt

def plot_confusion_matrix(cm, num_classes, title='Confusion matrix'):
    print('Title: ', title)
    print(cm)
    
## Show confusion matrix
# Training dataset
predict_train = model.predict(x_train)
# Convert the one-hot vectors to the corresponding classes.
predict_train = np.argmax(predict_train, axis=1)
y_train = np.argmax(y_train, axis=1)
# Build confusion matrix.
confusion_mx = confusion_matrix(y_train, predict_train)
plot_confusion_matrix(confusion_mx, num_classes=num_classes, title='Confusion matrix - training set')

# Developing dataset
predict_dev = model.predict(x_dev)
# Convert the one-hot vectors to the corresponding classes.
predict_dev = np.argmax(predict_dev, axis=1)
y_dev = np.argmax(y_dev, axis=1)
# Build confusion matrix.
confusion_mx = confusion_matrix(y_dev, predict_dev)
plot_confusion_matrix(confusion_mx, num_classes=num_classes, title='Confusion matrix - developing set')


Title:  Confusion matrix - training set
[[6249   35    3    0    0    0    0    0    0    0]
 [   0 6325    0    0    0    0    0    0    0    0]
 [   1    0 6331    1    0    0    1    1    0    0]
 [   0    0    0 6367    0    0    0    2    0    0]
 [   0    0    0    0 6349    0    0    0    0    0]
 [   0    0    0    2    2 6291    0    0    0    0]
 [   0    0    0    0    0    0 6306    2    0    8]
 [   0    1    0   10    0    0    5 6283    0    1]
 [   1    1    1    0    1    0    0    0 6313    1]
 [   0    0    0    0    0    0    5    0    0 6317]]
Title:  Confusion matrix - developing set
[[721  15   1   0   0   0   0   0   0   0]
 [  3 696   0   0   0   0   0   0   0   0]
 [  1   1 686   0   0   0   0   0   1   0]
 [  0   0   0 652   0   1   0   2   0   0]
 [  0   1   2   0 670   0   1   0   1   0]
 [  1   0   0   2   1 724   0   1   0   0]
 [  0   0   0   0   0   0 695   2   0  11]
 [  0   0   0   3   0   0   5 716   0   0]
 [  1   0   0   0   1   0   0   0 704   0]
